{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "standard-workload.fullname" . }}-secret
  labels:
    {{- include "standard-workload.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval | quote }}
  secretStoreRef:
    kind: SecretStore
    name: {{ .Values.externalSecret.secretStoreName }}
  target:
    name: {{ include "standard-workload.fullname" . }}-secret
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: {{ .Values.externalSecret.key }}
      remoteRef:
        key: {{ .Values.externalSecret.sourceSecretName }}
        property: {{ .Values.externalSecret.sourceProperty }}
{{- end }}
