{{- if .Values.externalSecret.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.externalSecret.authServiceAccountName }}
  labels:
    {{- include "standard-workload.labels" . | nindent 4 }}
automountServiceAccountToken: false
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ .Values.externalSecret.secretStoreName }}
  labels:
    {{- include "standard-workload.labels" . | nindent 4 }}
spec:
  provider:
    kubernetes:
      remoteNamespace: {{ .Values.externalSecret.sourceNamespace }}
      server:
        url: "kubernetes.default"
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt
      auth:
        serviceAccount:
          name: {{ .Values.externalSecret.authServiceAccountName }}
          namespace: {{ .Release.Namespace }}
{{- end }}
