apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "standard-workload.fullname" . }}
  labels:
    {{- include "standard-workload.labels" . | nindent 4 }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
